movies/infomovies/urls.py
from django.urls import path
from infomovies.views import ping, MoviesList, MoviesDetails
from .views import HomeViewMovie

urlpatterns = [
    #path('', HomeViewMovie.as_view(), name='home'),
    path("status/", ping, name="ping"),
    path("api/movies/", MoviesList.as_view(), name="movies_list"),
    path("api/movies/<int:pk>/", MoviesDetails.as_view()),
]

movies/movies/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('info/', include('infomovies.urls')),
    
]

movies/users/urls.py
from  django.urls import path
from .views import HomeView, LoginView, LogoutView, SigninView



app_name = 'users'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signin/', SigninView.as_view(), name='signin'),
   
]

movies/infomovies/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class Movies(models.Model):
    title = models.CharField(max_length=100)
    year = models.IntegerField()
    genre = models.CharField(max_length=100)
    classification = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Movie"
        verbose_name_plural = "Movies"
    
    def __str__(self):
        return self.title

movies/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()

    def __str__(self):
        return self.user.get_username()

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def update_profile(sender, instance, **kwargs):
    instance.profile.save()

movies/users/forms.py
import email
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

class LoginForm(AuthenticationForm):
    pass

class SigninForm(UserCreationForm):
    email = forms.EmailField(label='email')
    first_name = forms.CharField(label='first name')
    last_name = forms.CharField(label='last name')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

movies/infomovies/views.py
from django.http import JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import MovieSerializer
from .models import Movies
from django.views.generic import TemplateView

def ping(request):
    data = {"status": "ok!"}
    return JsonResponse(data)

class MoviesList(APIView):

    def get(self, request):
        movies = Movies.objects.all().order_by('created_at')
        serializer = MovieSerializer(movies, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request):
        serializer = MovieSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class MoviesDetails(APIView): 

    def get(self, request, pk):
        movie = Movies.objects.filter(pk=pk).first()
        serializer = MovieSerializer(movie)
        if movie:
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_404_NOT_FOUND)

    def put(self, request, pk):
        movie = Movies.objects.filter(pk=pk).first()
        serializer = MovieSerializer(movie, data=request.data)
        if movie and serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk): 
        movie = Movies.objects.filter(pk=pk).first()
        if movie:
            serializer = MovieSerializer(movie)
            movie.delete()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(status=status.HTTP_404_NOT_FOUND)

class HomeViewMovie(TemplateView):
    template_name = 'infomovies/pagez.html'

movies/users/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, RedirectView, FormView
from .forms import LoginForm, SigninForm
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User


class HomeView(TemplateView):
    template_name = 'users/home.html'


class LoginView(FormView):
    form_class = LoginForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('users:home')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)


class LogoutView(RedirectView):
    url = reverse_lazy('users:home')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class SigninView(CreateView):
    form_class = SigninForm
    model = User
    template_name = 'users/signin.html'
    success_url = reverse_lazy('users:home')

movies/infomovies/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block tittle %} Index {% endblock %}</title>
</head>
<body>
    
    {% block content %}
    {% endblock %}
</body>
</html>

movies/infomovies/templates/infomovies/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}


{% block content %}
<div>
  <h1>Welcome</h1>
  <p>This is a aplication Web for Educational Purposes Only</p>
  <hr>
</div>
<div>
  <h3>Informacion de la actividad</h3>
  <p> elementos en el codigo Aplicacion Infomovies</p>
  <ul>Testing con pytest</ul>
  <ul>Celery</ul>
  
  <a href="#">Movies</a>
</div>
{% endblock content %}

movies/infomovies/templates/infomovies/pagez.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}


{% block content %}
<div>
  <h1>Welcome</h1>
  <p>This is a aplication Web for Educational Purposes Only</p>
  <hr>
</div>
<div>
  <h3>Apps</h3>
  <h3>Informacion de la actividad</h3>
    <p> elementos en el codigo Aplicacion Infomovies</p>
    <ul>Testing con pytest</ul>
    <ul>Celery</ul>
    <ul>introduccion a rest-framework</ul>
  <a href="#">Movies</a>
</div>
{% endblock content %}

movies/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS v5.0.2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block tittle %} Index {% endblock %} </title>
  </head>
  <body>
        {% if user.is_autenticated %}
            <div class="px-4">
                <p> Welcome, {{ user.username }}, Thanks for loggin in.</p>
                <a name=""  class="btn btn-warning" href="{% url 'users:home' %}" role="button">Home</a>
                <a name=""  class="btn btn-danger" href="{% url 'users:logout' %}" role="button">Logout</a>
            </div>
            
            
        {% else %}
            <div class="px-4">
                <p>Welcome, new user. Please log in</p>
                <a name=""  class="btn btn-info" href="{% url 'users:signin' %}" role="button">Signin</a>
                <a name=""  class="btn btn-success" href="{% url 'users:login' %}" role="button">Login</a>
            </div>
            
            
            
        {% endif %}
        {% block content %}
        {% endblock %} 
      
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

movies/templates/users/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}


{% block content %}
<div class="text-center">
  <h1>Welcome</h1>
  <p>This is a aplication Web for Educational Purposes Only</p>
  <hr>
</div>
<div class="px-4">
  <h3>Note</h3>
  <p>This is an aplication make for django advance in the code yo can see:</p>
  <ul>Celery with a small function for test Purposes</ul>
  <ul>You can se a working login at the top of this page using signal and advance forms</ul>
  <ul>you can run pytest in the console, you must run first the enviroment before start the pytest</ul>
  <ul>Hint: theres a basic Django rest-framework for the movies app!!</ul>
  <ul>in that page you can add movies in json format</ul>
  <ul>
    example:
  {
    "id": 1,
    "title": "The Fast And The Furious",
    "year": 2001,
    "genre": "Action",
    "classification": "PG-13",
  }
  </ul>
  
  <a name=""  class="btn btn-primary" href="{% url 'movies_list' %}" role="button">RestFramework</a>

  
  
  

</div>
<h2>By Jorge Zetien</h2>
{% endblock content %}  
  

movies/templates/users/login.html
{% extends 'base.html' %}
{% block tilte_modal %}Login{% endblock tilte_modal %}

{% block content %}
<form method="POST" action="{% url 'users:login' %}">{% csrf_token %}
  <div>
    {{ form.as_p }}
    <div>
      <button class="btn btn-success" type="submit">Login</button>
    </div>
  </div>
</form>
{% endblock content %}

movies/templates/users/signin.html
{% extends 'base.html' %}
{% block tilte %}Signin{% endblock tilte %}

{% block content %}
<form method="POST" action="{% url 'users:signin' %}" class="">{% csrf_token %}
  <div class="form-group">
    {{ form.as_p}}
    <div>
      <button type="submit">Signin</button>
    </div>
  </div>
</form>
{% endblock content %}